import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentSession, prisma } from "@/lib/auth";

const statusTone: Record<string, string> = { AVAILABLE: "bg-emerald-50 text-emerald-700", PENDING: "bg-amber-50 text-amber-700", NEW: "bg-blue-50 text-blue-700", VISIT_SCHEDULED: "bg-violet-50 text-violet-700", VISIT_COMPLETED: "bg-emerald-50 text-emerald-700" };

export default async function AdminDashboardPage() {
  const session = await getCurrentSession();
  if (!session) redirect("/login?redirect=/admin");
  if (session.user.role.toUpperCase() !== "ADMIN") redirect("/dashboard");

  const today = new Date().toISOString().slice(0, 10);
  const [totalProperties, activeListings, pendingReview, totalLeads, newLeads, upcomingVisits, completedVisits, totalOwners, properties, enquiries, visits] = await Promise.all([
    prisma.property.count(), prisma.property.count({ where: { status: "AVAILABLE" } }), prisma.property.count({ where: { status: "PENDING" } }), prisma.enquiry.count(), prisma.enquiry.count({ where: { status: "NEW" } }), prisma.enquiry.count({ where: { status: "VISIT_SCHEDULED", visitDate: { gte: today } } }), prisma.enquiry.count({ where: { status: "VISIT_COMPLETED" } }), prisma.user.count({ where: { role: { in: ["OWNER", "BROKER"] } } }),
    prisma.property.findMany({ orderBy: { createdAt: "desc" }, take: 5, select: { id: true, propertyType: true, bhk: true, sector: true, monthlyRent: true, status: true, createdAt: true, media: { where: { type: "IMAGE" }, orderBy: { position: "asc" }, take: 1, select: { secureUrl: true } } } }),
    prisma.enquiry.findMany({ orderBy: { createdAt: "desc" }, take: 5, select: { id: true, name: true, status: true, visitDate: true, visitTime: true, createdAt: true, property: { select: { id: true, bhk: true, propertyType: true, sector: true } } } }),
    prisma.enquiry.findMany({ where: { visitDate: { not: null } }, orderBy: [{ visitDate: "asc" }, { visitTime: "asc" }], take: 5, select: { id: true, status: true, visitDate: true, visitTime: true, property: { select: { id: true, bhk: true, propertyType: true, sector: true } } } }),
  ]);
  const stats: Array<[string, number, string]> = [["Total properties", totalProperties, "/admin/properties"], ["Active listings", activeListings, "/properties"], ["Pending review", pendingReview, "/admin/properties"], ["Owners & brokers", totalOwners, "/admin/owners"], ["Tenant leads", totalLeads, "/enquiries"], ["New / unread leads", newLeads, "/enquiries?status=NEW"], ["Upcoming visits", upcomingVisits, "/enquiries?filter=upcoming-visits"], ["Completed visits", completedVisits, "/enquiries?filter=completed-visits"]];
  const activity = [...properties.map((item) => ({ id: `p-${item.id}`, text: `${item.bhk} ${item.propertyType} listing recorded`, date: item.createdAt })), ...enquiries.map((item) => ({ id: `e-${item.id}`, text: `Enquiry #${item.id} is ${item.status.replaceAll("_", " ").toLowerCase()}`, date: item.createdAt }))].sort((a, b) => b.date.getTime() - a.date.getTime()).slice(0, 5);

  return <main className="app-page min-h-screen bg-gradient-to-b from-slate-100 via-slate-50 to-white text-slate-900">
    <header className="border-b border-slate-200 bg-white/95"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-5 sm:px-6"><Link href="/admin" className="text-xl font-bold">Gurugram<span className="text-slate-500">Property</span></Link><div className="flex items-center gap-4 text-sm font-semibold text-slate-600"><span className="hidden sm:inline">Admin panel</span><Link href="/dashboard" className="hover:text-slate-950">Dashboards</Link></div></div></header>
    <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 sm:py-12"><div className="rounded-3xl bg-gradient-to-r from-slate-950 via-slate-900 to-blue-950 p-6 text-white shadow-xl sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-200">Platform operations</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Good to see you, {session.user.name}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">A real-time view of property reviews, tenant enquiries, and visit progress.</p></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([label, value, href]) => <Link key={label} href={href} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-md"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-2 text-xs font-semibold text-blue-700">Open records →</p></Link>)}</div>
      <div className="mt-6 grid gap-6 lg:grid-cols-2">
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-4"><div><h2 className="text-lg font-bold">Recent properties</h2><p className="text-sm text-slate-500">Latest listing activity</p></div><Link href="/admin/properties" className="text-sm font-semibold text-blue-700">Review pending</Link></div>{properties.length === 0 ? <p className="mt-6 rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">No properties have been submitted yet.</p> : <div className="mt-4 divide-y divide-slate-100">{properties.map((property) => <Link key={property.id} href={property.status === "AVAILABLE" ? `/property/${property.id}` : "/admin/properties"} className="flex min-w-0 items-center gap-3 py-4 hover:bg-slate-50"><div className="h-12 w-16 shrink-0 overflow-hidden rounded-xl bg-slate-100">{property.media[0] && <img src={property.media[0].secureUrl} alt="" className="h-full w-full object-cover" />}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{property.bhk} {property.propertyType}</p><p className="truncate text-sm text-slate-500">{property.sector} · ₹{property.monthlyRent.toLocaleString("en-IN")}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${statusTone[property.status] || "bg-slate-100 text-slate-700"}`}>{property.status}</span></Link>)}</div>}</section>
        <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-4"><div><h2 className="text-lg font-bold">Recent leads & enquiries</h2><p className="text-sm text-slate-500">Latest tenant activity</p></div><Link href="/admin/leads" className="text-sm font-semibold text-blue-700">Manage leads</Link></div>{enquiries.length === 0 ? <p className="mt-6 rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">No enquiries have been received yet.</p> : <div className="mt-4 divide-y divide-slate-100">{enquiries.map((enquiry) => <Link key={enquiry.id} href={`/enquiries?enquiryId=${enquiry.id}`} className="block py-4 hover:bg-slate-50"><div className="flex justify-between gap-3"><p className="truncate font-semibold">{enquiry.name}</p><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${statusTone[enquiry.status] || "bg-slate-100 text-slate-700"}`}>{enquiry.status.replaceAll("_", " ")}</span></div><p className="mt-1 text-sm text-slate-500">{enquiry.property.bhk} {enquiry.property.propertyType} · {enquiry.property.sector}</p></Link>)}</div>}</section>
      </div>
      <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Recent visits</h2><p className="text-sm text-slate-500">Scheduled and completed appointments</p></div><Link href="/admin/visits" className="text-sm font-semibold text-blue-700">Open visits</Link></div>{visits.length === 0 ? <p className="mt-6 rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">No visits have been scheduled yet.</p> : <div className="mt-4 space-y-3">{visits.map((visit) => <Link key={visit.id} href={`/enquiries?enquiryId=${visit.id}`} className="block rounded-2xl bg-slate-50 p-4 hover:bg-blue-50"><div className="flex justify-between gap-3"><p className="font-semibold">{visit.property.bhk} {visit.property.propertyType}</p><span className="text-xs font-semibold text-slate-500">{visit.status.replaceAll("_", " ")}</span></div><p className="mt-1 text-sm text-slate-500">{visit.property.sector} · {visit.visitDate}{visit.visitTime ? ` at ${visit.visitTime}` : ""}</p></Link>)}</div>}</section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Recent activity</h2><p className="text-sm text-slate-500">Derived from recorded platform events.</p>{activity.length === 0 ? <p className="mt-6 rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">No recent activity.</p> : <div className="mt-5 space-y-4">{activity.map((item) => <div key={item.id} className="flex gap-3"><span className="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full bg-blue-600" /><div><p className="text-sm font-medium">{item.text}</p><p className="mt-1 text-xs text-slate-500">{item.date.toLocaleDateString("en-IN")}</p></div></div>)}</div>}</section></div>
    </section>
  </main>;
}
